### ISSUE TITLE
Using phonegap-sms-plugin with Bulid

### ISSUE THREAD

**Issue by useappility** [aharris88/phonegap-sms-plugin#10]
I am using build.phonegap.com to upload my project. There is no the phonegap-sms-plugin within the tab "plugins". How can I upload it into mo my project?

**Comment by aharris88** [comment]
Please see issue #53

**Comment by dbaq** [comment]
Let's follow up this issue over there: https://github.com/cordova-sms/cordova-sms-plugin/issues/2
