### ISSUE TITLE
sms is not defined

### ISSUE THREAD

**Issue by fredericks** [aharris88/phonegap-sms-plugin#12]
Hi, just a question, I tried this plugin last week and it seemed I got it working. But now I always get "sms is not defined" when I try to use the sms object. I followed your instructions, but it's not working anymore.

I did these simple steps:
1. Created new phonegap app (phonegap create sms)
2. Added plugin (phonegap local plugin add https://github.com/aharris88/phonegap-sms-plugin.git)
3. Put your code to send sms in index.html (replacing the jquery part), and I always get the error (sms is not defined).
4. build for android

I get the same error both on the emulator and on the phone
Did I do something wrong?
thanks

**Comment by satyagvns** [comment]
Hi aharris88,

I started using sms plugin to my phonegap, I am facing the above issue like "sms not defined".

# Environment:

OS : UBUNTU
Added File : config.xml
Line: 
<gap:plugin name="org.apache.cordova.vibration" />
    <gap:plugin name="com.cordova.plugins.sms" version="0.1.1" />
    <icon src="icon.png" />

But When run command "phonegap serve" and checking in my console. It is not showing in loaded services.

What is wrong I am doing.

Please help me.

**Comment by agarrharr** [comment]
This repo has actually moved. You can submit a new issue over here: https://github.com/cordova-sms/cordova-sms-plugin/issues/new
