### ISSUE TITLE
Support for reading messages and for tracking new messages

### ISSUE THREAD

**Issue by leandroal** [aharris88/phonegap-sms-plugin#36]
Is this plugin support read/track messages? I would like to make this functionality available for BlackBerry 10 and Android. Are you interested on this? If so, I can implement this function for BlackBerry 10, at least. Please, confirm and tell me the best approach for this.

**Comment by aharris88** [comment]
Please see issue #53

**Comment by dbaq** [comment]
Please, let's follow up on the new repo https://github.com/cordova-sms/cordova-sms-plugin
