### ISSUE TITLE
IOS 8 support

### ISSUE THREAD

**Issue by ninapratiwi** [aharris88/phonegap-sms-plugin#39]
So recently I use AngularJs to use this plugin

Here's the code:
    $scope.sendText = function(){
                    
                    var intent = "INTENT";
                    var success = function(){alert("Sent SMS successfully"); };
                    var error = function(e){alert("Message Failed "+e); };
                    alert("Values:\nNumber:"+$scope.number+
                            "\nMessage:"+$scope.text+
                            "\nIntent:"+intent);

                    sms.send($scope.number, $scope.text, intent, success, error);
    };

No error but not running..
it doesn't return success or error..

Checked the plugin is not broken..
everything is inside..

does it because I run it on ios 8..?

**Comment by ritikk** [comment]
+1 
not working with ios8

**Comment by aharris88** [comment]
Please see issue #53

**Comment by dbaq** [comment]
let's follow up there: https://github.com/cordova-sms/cordova-sms-plugin/issues/5
