### ISSUE TITLE
convert break line into plain sms text

### ISSUE THREAD

**Issue by datomnurdin** [aharris88/phonegap-sms-plugin#41]
Hi, I just got this issue. How I can send plain sms text without ```<br/>``` ?

My message value is 

```
Your TAC number was
<br/ >
<br/ >
stole!!

```

What I want is like this

```
Your TAC number was

stole!!

```

How possible is that?

**Comment by aharris88** [comment]
Please see issue #53

**Comment by dbaq** [comment]
let's follow up there: https://github.com/cordova-sms/cordova-sms-plugin/issues/6
