### ISSUE TITLE
Success callback only called once (android)

### ISSUE THREAD

**Issue by samkuhn** [aharris88/phonegap-sms-plugin#50]
There is a mention of this near the bottom of closed issue (#29) but the problem still persists, so I'm opening a new one.

The success callback fires the first time send is called (as expected) - but not on subsequent calls. This problem only occurs on android. The callbacks fire every time as expected under IOS.

**Comment by aharris88** [comment]
Please see issue #53

**Comment by dbaq** [comment]
@samkuhn if it is still a valid issue, please open a new one on https://github.com/cordova-sms/cordova-sms-plugin
