### ISSUE TITLE
callbacks called with same context

### ISSUE THREAD

**Issue by alvare** [aharris88/phonegap-sms-plugin#51]
This is not the same as https://github.com/aharris88/phonegap-sms-plugin/issues/50

It seems every callback is called with the same context, meaning for example a `this` binding will reference an old object in a second callback.

This could be caused by having `keepCallback(true)` before every `callbackContext.sendPluginResult`
in Sms.java: https://github.com/aharris88/phonegap-sms-plugin/blob/master/src/android/Sms.java#L62

**Comment by alvare** [comment]
Effectively, commenting said line fixes it. But I have no knowledge of Android programming and can't fully understand the consequences of the modification.

**Comment by aharris88** [comment]
Please see issue #53

**Comment by dbaq** [comment]
let's follow up there: https://github.com/cordova-sms/cordova-sms-plugin/issues/10
